### ISSUE TITLE
Several enhancement requests

### ISSUE THREAD

**Issue by chocolatechipcats** [mapozyan/caps#3]
Cross-posted from the Power Search thread on MobileRead, in case it was missed there:

1. An option to set the path for ElasticSearch, so that if it isn't running it can launch it instead of just throwing an error about being unable to contact the service.
2. Being able to search only the currently viewed (or selected, if that's more doable) books. This could be added as a dropdown menu.
3. On the topic of the menus, the icon is extremely low-contrast in dark mode (I only just realized there's a magnifying glass). An alternate icon for dark mode would be nice.
4. Add the two indexing options as dropdown menu I was hoping that I could incorporate re-indexing into one of my action chains (not entirely sure it'll work, but it's worth a try).

Thank you!

**Comment by mapozyan** [comment]
Thanks! Will try to implement it.

**Comment by mapozyan** [comment]
Done.
