### ISSUE TITLE
Indexing freezes on a particular book

### ISSUE THREAD

**Issue by Basemaly-pratt** [mapozyan/caps#6]
Hello. Thank you for your wonderful plugin! I have one issue when indexing a particular .epub book. The indexing process freezes and cancelling it doesn't work. I end up having to force quit and restarting Calibre. Any suggestions on what I can do? Is there a way to flag a particular .epub so it doesn't get indexed? Thank you.

**Comment by mapozyan** [comment]
Thank you for your report. Can you please send on my email this particular file so I would be able to test it?
The idea of marking books for exclusion sounds great and I will implement it with next release.
